/**
 * Israeli cities list for candidate ticket and job filters
 * Shared across multiple components
 */

export const israeliCities = [
  'Tel Aviv-Yafo',
  'Jerusalem',
  'Haifa',
  'Rishon LeZion',
  'Petah Tikva',
  'Ashdod',
  'Netanya',
  'Beer Sheva',
  'Holon',
  'Ramat Gan',
  'Ashkelon',
  'Rehovot',
  'Herzliya',
  'Kfar Saba',
  'Bat Yam',
  'Ramat HaSharon',
  'Lod',
  'Ness Ziona',
  'Eilat',
  'Nahariya',
  'Acre',
  'Tiberias',
  'Nazareth',
  'Sderot',
  'Dimona',
  'Kiryat Gat',
  'Kiryat Shmona',
  'Ma\'alot-Tarshiha',
  'Ofakim',
  'Arad',
  'Karmiel',
  'Kiryat Bialik',
  'Kiryat Motzkin',
  'Kiryat Yam',
  'Kiryat Ata',
  'Kiryat Tivon',
  'Yokneam Illit',
  'Migdal HaEmek',
  'Nesher',
  'Tirat Carmel',
  'Yokneam',
  'Ma\'ale Adumim',
  'Ma\'alot',
  'Kiryat Malakhi',
  'Kiryat Ono',
  'Givatayim',
  'Rosh HaAyin',
  'Modi\'in',
  'Yavne',
  'Or Yehuda',
  'Kfar Yona',
  'Mazkeret Batya',
  'Gedera',
  'Ra\'anana',
  'Hod HaSharon',
  'Even Yehuda',
  'Tzur Yigal',
  'Kadima-Zoran',
  'Tel Mond',
  'Kfar Hess',
  'Beit Dagan',
  'Gan Yavne',
  'Kfar Menahem',
  'Kfar Bilu',
  'Kfar Malal'
];

