/**
 * Technical skills options for projects
 * Shared across multiple components
 */

export const technicalSkillsOptions = [
  'Actix Web',
  'Angular',
  'Ansible',
  'Apache',
  'Apache Kafka',
  'Apache Spark',
  'APM Tools',
  'Apollo',
  'ASP.NET Core',
  'Assembly',
  'AWS',
  'Azure',
  'Bash scripting',
  'Bitbucket',
  'Bitcoin',
  'Blockchain',
  'Bootstrap',
  'C',
  'C# (.NET Core)',
  'C++',
  'Caching Strategies',
  'Capacitor',
  'Cassandra',
  'CDN',
  'Chai',
  'Clojure',
  'Computer Graphics',
  'Cordova',
  'CORS',
  'CouchDB',
  'Cryptocurrency',
  'Cryptography',
  'CSS3',
  'Cypress',
  'Dart',
  'Design Patterns',
  'DirectX',
  'Django',
  'Docker',
  'Docker Compose',
  'Domain-Driven Design',
  'DynamoDB',
  'Elasticsearch',
  'Elixir',
  'Emacs',
  'Entity Framework',
  'Erlang',
  'Ethereum',
  'Event-Driven Architecture',
  'Express.js',
  'FastAPI',
  'Fastify',
  'Fiber',
  'Figma',
  'Firebase',
  'Firestore',
  'Flask',
  'Flutter',
  'Game Development',
  'Gin',
  'Git',
  'GitHub',
  'GitHub Actions',
  'GitLab',
  'GitLab CI',
  'Go (Golang)',
  'Google Cloud Platform',
  'Google Colab',
  'GraphQL',
  'gRPC',
  'Haskell',
  'Hibernate',
  'HTML5',
  'Hugging Face',
  'InfluxDB',
  'Insomnia',
  'IntelliJ IDEA',
  'Ionic',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'Jira',
  'jQuery',
  'JUnit',
  'Jupyter',
  'Keras',
  'Kotlin',
  'Kotlin (Android)',
  'Kubernetes',
  'LangChain',
  'Laravel',
  'Linux',
  'Load Balancing',
  'Logging',
  'MariaDB',
  'Material-UI',
  'MATLAB',
  'Microservices',
  'Mocha',
  'Monitoring',
  'Mongoose',
  'MongoDB',
  'MySQL',
  'Neo4j',
  'NestJS',
  'Nginx',
  'Node.js',
  'Notion',
  'NumPy',
  'OAuth2',
  'OpenAI API',
  'OpenCV',
  'OpenGL',
  'OWASP',
  'Pandas',
  'Parcel',
  'Penetration Testing',
  'Performance Optimization',
  'Perl',
  'PHP',
  'PostgreSQL',
  'Postman',
  'PowerShell',
  'Prisma',
  'PyCharm',
  'Python',
  'PyTorch',
  'pytest',
  'RabbitMQ',
  'R',
  'React',
  'React Native',
  'Redis',
  'RESTful APIs',
  'Rocket',
  'RSpec',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'Sass/SCSS',
  'Scala',
  'Scikit-learn',
  'Selenium',
  'Sequelize',
  'Serverless',
  'Smart Contracts',
  'Socket.io',
  'SOLID Principles',
  'Solidity',
  'SQLAlchemy',
  'SQLite',
  'Spring Boot',
  'Sublime Text',
  'Svelte',
  'Swift',
  'Swift (iOS)',
  'Tailwind CSS',
  'TensorFlow',
  'Terraform',
  'Trello',
  'TypeORM',
  'TypeScript',
  'Unity',
  'Unreal Engine',
  'Vim',
  'Vite',
  'Vue.js',
  'VS Code',
  'Vulkan',
  'Web3',
  'Webpack',
  'WebSockets',
  'WebStorm',
  'Xamarin'
];

